<?php
/**
 * Created by PhpStorm.
 * User: splus
 * Date: 12/25/18
 * Time: 11:10
 */

// Register Custom Post Type
function custom_post_type() {

    /*policy custom post type*/
    $labels = array(
        'name'                  => _x( 'Resort Regulations', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Regulation', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Regulations', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Regulations', TEXT_DOMAIN ),
        'archives'              => __( 'Regulations Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Regulations Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Regulation:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Regulations', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Regulation', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Regulation', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Regulation', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Regulation', TEXT_DOMAIN ),
        'view_item'             => __( 'View Regulation', TEXT_DOMAIN ),
        'view_items'            => __( 'View Regulations', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Regulation', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );


    $args = array(
        'label'                 => __( 'Regulations', TEXT_DOMAIN ),
        'description'           => __( 'Regulations', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title', 'editor' ),
        'hierarchical'          => false,
        'public'                => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 3,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'page',
        'menu_icon'             => 'dashicons-editor-ul',
    );
    register_post_type( 'policy', $args );


    $labels = array(
        'name'                  => _x( 'Policies', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Policy', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Policies', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Policies', TEXT_DOMAIN ),
        'archives'              => __( 'Policies Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Policies Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Policy:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Policies', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Policy', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Policy', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Policy', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Policy', TEXT_DOMAIN ),
        'view_item'             => __( 'View Policy', TEXT_DOMAIN ),
        'view_items'            => __( 'View Policies', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Policy', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );

    $args = array(
        'label'                 => __( 'Policies', TEXT_DOMAIN ),
        'description'           => __( 'Policies', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title', 'editor' ),
        'hierarchical'          => false,
        'public'                => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 3,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'page',
        'menu_icon'             => 'dashicons-sos',
    );
    register_post_type( 'regulations-post', $args );


    /*about custom post type*/
    $labels = array(
        'name'                  => _x( 'About Timeline', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'About Timeline', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'About Timeline', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'About Timeline', TEXT_DOMAIN ),
        'archives'              => __( 'About Timeline Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'About Timeline Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent About:', TEXT_DOMAIN ),
        'all_items'             => __( 'All About Timeline', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New About Timeline', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New About', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit About', TEXT_DOMAIN ),
        'update_item'           => __( 'Update About', TEXT_DOMAIN ),
        'view_item'             => __( 'View About', TEXT_DOMAIN ),
        'view_items'            => __( 'View About', TEXT_DOMAIN ),
        'search_items'          => __( 'Search About', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );
    $args = array(
        'label'                 => __( 'About', TEXT_DOMAIN ),
        'description'           => __( 'About', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title', 'editor','thumbnail' ),
        'hierarchical'          => false,
        'public'                => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 4,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'page',
        'menu_icon'             => 'dashicons-editor-video',
    );
    register_post_type( 'about-post', $args );

    $labels = array(
        'name'                  => _x( 'Offers', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Offers', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Offers', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Offers', TEXT_DOMAIN ),
        'archives'              => __( 'Item Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Item Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Item:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Items', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Item', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Item', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'             => __( 'View Item', TEXT_DOMAIN ),
        'view_items'            => __( 'View Items', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Item', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );
    $args = array(
        'label'                 => __( 'Offers', TEXT_DOMAIN ),
        'description'           => __( 'Offers', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title', 'thumbnail','excerpt' ),
        'hierarchical'          => false,
        'public'                => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 4,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => true,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'page',
        'menu_icon'             => 'dashicons-clipboard',
    );
    register_post_type( 'press-release-post', $args );



    $labels = array(
        'name'                  => _x( 'Near by', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Near by', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Near by', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Near by', TEXT_DOMAIN ),
        'archives'              => __( 'Item Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Item Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Item:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Items', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Item', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Item', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'             => __( 'View Item', TEXT_DOMAIN ),
        'view_items'            => __( 'View Items', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Item', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );
    $args = array(
        'label'                 => __( 'Near by', TEXT_DOMAIN ),
        'description'           => __( 'Near by', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title', 'thumbnail','excerpt' ),
        'hierarchical'          => false,
        'public'                => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 4,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => true,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'page',
        'menu_icon'             => 'dashicons-migrate',
    );
    register_post_type( 'nearby-post', $args );


    $labels = array(
        'name'                  => _x( 'Get here', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Get here', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Get here', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Get here', TEXT_DOMAIN ),
        'archives'              => __( 'Item Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Item Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Item:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Items', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Item', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Item', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'             => __( 'View Item', TEXT_DOMAIN ),
        'view_items'            => __( 'View Items', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Item', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );
    $args = array(
        'label'                 => __( 'Get here', TEXT_DOMAIN ),
        'description'           => __( 'Get here', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title', 'thumbnail' ),
        'taxonomies'            => array('gethere_category'),
        'hierarchical'          => false,
        'public'                => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 4,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
        'menu_icon'             => 'dashicons-phone',
    );
    register_post_type( 'gethere-post', $args );


    $labels = array(
        'name'                  => _x( 'Gallery Slider', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Gallery Slider', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Gallery Slider', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Gallery Slider', TEXT_DOMAIN ),
        'archives'              => __( 'Item Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Item Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Item:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Items', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Item', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Item', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'             => __( 'View Item', TEXT_DOMAIN ),
        'view_items'            => __( 'View Items', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Item', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );
    $args = array(
        'label'                 => __( 'Gallery Slider', TEXT_DOMAIN ),
        'description'           => __( 'Gallery Slider', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title' ),
        'hierarchical'          => false,
        'public'                => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 4,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
        'menu_icon'             => 'dashicons-format-gallery',
    );
    register_post_type( 'gallery-post', $args );

    $labels = array(
        'name'                  => _x( 'Gallery Grid', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Gallery Grid', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Gallery Grid', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Gallery Grid', TEXT_DOMAIN ),
        'archives'              => __( 'Item Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Item Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Item:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Items', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Item', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Item', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'             => __( 'View Item', TEXT_DOMAIN ),
        'view_items'            => __( 'View Items', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Item', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );
    $args = array(
        'label'                 => __( 'Gallery Grid', TEXT_DOMAIN ),
        'description'           => __( 'Gallery Grid', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title','editor' ),
        'hierarchical'          => false,
        'public'                => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 4,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
        'menu_icon'             => 'dashicons-images-alt2',
    );
    register_post_type( 'gallery-grid-post', $args );

    $labels = array(
        'name'                  => _x( 'Meeting & Event', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Meeting & Event', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Meeting & Event', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Meeting & Event', TEXT_DOMAIN ),
        'archives'              => __( 'Item Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Item Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Item:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Items', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Item', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Item', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'             => __( 'View Item', TEXT_DOMAIN ),
        'view_items'            => __( 'View Items', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Item', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );
    $args = array(
        'label'                 => __( 'Meeting & Event', TEXT_DOMAIN ),
        'description'           => __( 'Meeting & Event', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title','editor','thumbnail' ),
        'hierarchical'          => false,
        'public'                => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 4,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
        'menu_icon'             => 'dashicons-megaphone',
    );
    register_post_type( 'event-post', $args );

    $labels = array(
        'name'                  => _x( 'Dining Menu', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Dining Menu', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Dining Menu', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Dining Menu', TEXT_DOMAIN ),
        'archives'              => __( 'Item Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Item Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Item:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Items', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Item', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Item', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'             => __( 'View Item', TEXT_DOMAIN ),
        'view_items'            => __( 'View Items', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Item', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );
    $args = array(
        'label'                 => __( 'Dining Menu', TEXT_DOMAIN ),
        'description'           => __( 'Dining Menu', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title','editor','thumbnail' ),
        'hierarchical'          => false,
        'public'                => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 4,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
        'menu_icon'             => 'dashicons-warning',
    );
    register_post_type( 'dining-menu-post', $args );

    $labels = array(
        'name'                  => _x( 'Dining Place', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Dining Place', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Dining Place', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Dining Place', TEXT_DOMAIN ),
        'archives'              => __( 'Item Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Item Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Item:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Items', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Item', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Item', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'             => __( 'View Item', TEXT_DOMAIN ),
        'view_items'            => __( 'View Items', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Item', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );
    $args = array(
        'label'                 => __( 'Dining Place', TEXT_DOMAIN ),
        'description'           => __( 'Dining Place', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title','editor','thumbnail' ),
        'hierarchical'          => false,
        'public'                => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 4,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
        'menu_icon'             => 'dashicons-location',
    );
    register_post_type( 'dining-place-post', $args );

    $labels = array(
        'name'                  => _x( 'Seasonal Offer', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Seasonal Offer', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Seasonal Offer', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Seasonal Offer', TEXT_DOMAIN ),
        'archives'              => __( 'Item Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Item Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Item:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Items', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Item', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Item', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'             => __( 'View Item', TEXT_DOMAIN ),
        'view_items'            => __( 'View Items', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Item', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );
    $args = array(
        'label'                 => __( 'Seasonal Offer', TEXT_DOMAIN ),
        'description'           => __( 'Seasonal Offer', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title','editor','thumbnail' ),
        'hierarchical'          => false,
        'public'                => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 4,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
        'menu_icon'             => 'dashicons-feedback',
    );
    register_post_type( 'dining-offer-post', $args );


    $labels = array(
        'name'                  => _x( 'Experience', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Experience', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Experience', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Experience', TEXT_DOMAIN ),
        'archives'              => __( 'Item Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Item Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Item:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Items', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Item', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Item', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'             => __( 'View Item', TEXT_DOMAIN ),
        'view_items'            => __( 'View Items', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Item', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );
    $args = array(
        'label'                 => __( 'Experience', TEXT_DOMAIN ),
        'description'           => __( 'Experience', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title','editor','thumbnail' ),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 4,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
        'rewrite'     => array( 'slug' => 'experience' ),
        'menu_icon'             => 'dashicons-editor-code',
    );
    register_post_type( 'experience-post', $args );

    $labels = array(
        'name'                  => _x( 'Room', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Room', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Room', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Room', TEXT_DOMAIN ),
        'archives'              => __( 'Item Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Item Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Item:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Items', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Item', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Item', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'             => __( 'View Item', TEXT_DOMAIN ),
        'view_items'            => __( 'View Items', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Item', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );
    $args = array(
        'label'                 => __( 'Room', TEXT_DOMAIN ),
        'description'           => __( 'Room', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title','editor','thumbnail','excerpt' ),
        'taxonomies'            => array('room_feature','room_utility'),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 4,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
        'rewrite'     => array( 'slug' => 'room' ),
        'menu_icon'             => 'dashicons-store',
    );
    register_post_type( 'room-post', $args );


    $labels = array(
        'name'                  => _x( 'Room Capacity', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Room Capacity', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Room Capacity', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Room Capacity', TEXT_DOMAIN ),
        'archives'              => __( 'Item Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Item Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Item:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Items', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Item', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Item', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'             => __( 'View Item', TEXT_DOMAIN ),
        'view_items'            => __( 'View Items', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Item', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );
    $args = array(
        'label'                 => __( 'Room Capacity', TEXT_DOMAIN ),
        'description'           => __( 'Room Capacity', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title' ),
        'hierarchical'          => false,
        'public'                => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 4,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
        'rewrite'     => array( 'slug' => 'room-capacity' ),
        'menu_icon'             => 'dashicons-move',
    );
    register_post_type( 'room-capacity-post', $args );



    $labels = array(
        'name'                  => _x( 'Calendar', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Calendar', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Calendar', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Calendar', TEXT_DOMAIN ),
        'archives'              => __( 'Item Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Item Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Item:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Items', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Item', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Item', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'             => __( 'View Item', TEXT_DOMAIN ),
        'view_items'            => __( 'View Items', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Item', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );
    $args = array(
        'label'                 => __( 'Calendar', TEXT_DOMAIN ),
        'description'           => __( 'Calendar', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title','thumbnail','excerpt' ),
        'hierarchical'          => false,
        'public'                => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 4,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
        'menu_icon'             => 'dashicons-calendar',
    );
    register_post_type( 'calendar-post', $args );


    $labels = array(
        'name'                  => _x( 'Exploration', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Exploration', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Exploration', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Exploration', TEXT_DOMAIN ),
        'archives'              => __( 'Item Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Item Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Item:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Items', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Item', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Item', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'             => __( 'View Item', TEXT_DOMAIN ),
        'view_items'            => __( 'View Items', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Item', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );
    $args = array(
        'label'                 => __( 'Exploration', TEXT_DOMAIN ),
        'description'           => __( 'Exploration', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title','thumbnail','excerpt' ),
        'taxonomies'            => array('room_feature','room_utility'),
        'hierarchical'          => false,
        'public'                => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 4,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
        'menu_icon'             => 'dashicons-media-archive',
    );
    register_post_type( 'exploration-post', $args );


    $labels = array(
        'name'                  => _x( 'Popup', 'Post Type General Name', TEXT_DOMAIN ),
        'singular_name'         => _x( 'Popup', 'Post Type Singular Name', TEXT_DOMAIN ),
        'menu_name'             => __( 'Popup', TEXT_DOMAIN ),
        'name_admin_bar'        => __( 'Popup', TEXT_DOMAIN ),
        'archives'              => __( 'Item Archives', TEXT_DOMAIN ),
        'attributes'            => __( 'Item Attributes', TEXT_DOMAIN ),
        'parent_item_colon'     => __( 'Parent Item:', TEXT_DOMAIN ),
        'all_items'             => __( 'All Items', TEXT_DOMAIN ),
        'add_new_item'          => __( 'Add New Item', TEXT_DOMAIN ),
        'add_new'               => __( 'Add New', TEXT_DOMAIN ),
        'new_item'              => __( 'New Item', TEXT_DOMAIN ),
        'edit_item'             => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'           => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'             => __( 'View Item', TEXT_DOMAIN ),
        'view_items'            => __( 'View Items', TEXT_DOMAIN ),
        'search_items'          => __( 'Search Item', TEXT_DOMAIN ),
        'not_found'             => __( 'Not found', TEXT_DOMAIN ),
        'not_found_in_trash'    => __( 'Not found in Trash', TEXT_DOMAIN ),
        'featured_image'        => __( 'Featured Image', TEXT_DOMAIN ),
        'set_featured_image'    => __( 'Set featured image', TEXT_DOMAIN ),
        'remove_featured_image' => __( 'Remove featured image', TEXT_DOMAIN ),
        'use_featured_image'    => __( 'Use as featured image', TEXT_DOMAIN ),
        'insert_into_item'      => __( 'Insert into item', TEXT_DOMAIN ),
        'uploaded_to_this_item' => __( 'Uploaded to this item', TEXT_DOMAIN ),
        'items_list'            => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation' => __( 'Items list navigation', TEXT_DOMAIN ),
        'filter_items_list'     => __( 'Filter items list', TEXT_DOMAIN ),
    );
    $args = array(
        'label'                 => __( 'Popup', TEXT_DOMAIN ),
        'description'           => __( 'Popup', TEXT_DOMAIN ),
        'labels'                => $labels,
        'supports'              => array( 'title','thumbnail' ),
        'taxonomies'            => array('room_feature','room_utility'),
        'hierarchical'          => false,
        'public'                => false,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 4,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
        'menu_icon'             => 'dashicons-admin-page',
    );
    register_post_type( 'popup-post', $args );
}
add_action( 'init', 'custom_post_type', 0 );




// Register Custom Taxonomy
function custom_taxonomy() {

    $labels = array(
        'name'                       => _x( 'Get Here Categories', 'Taxonomy General Name', TEXT_DOMAIN ),
        'singular_name'              => _x( 'Get Here Category', 'Taxonomy Singular Name', TEXT_DOMAIN ),
        'menu_name'                  => __( 'Categories', TEXT_DOMAIN ),
        'all_items'                  => __( 'All Items', TEXT_DOMAIN ),
        'parent_item'                => __( 'Parent Item', TEXT_DOMAIN ),
        'parent_item_colon'          => __( 'Parent Item:', TEXT_DOMAIN ),
        'new_item_name'              => __( 'New Item Name', TEXT_DOMAIN ),
        'add_new_item'               => __( 'Add New Item', TEXT_DOMAIN ),
        'edit_item'                  => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'                => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'                  => __( 'View Item', TEXT_DOMAIN ),
        'separate_items_with_commas' => __( 'Separate items with commas', TEXT_DOMAIN ),
        'add_or_remove_items'        => __( 'Add or remove items', TEXT_DOMAIN ),
        'choose_from_most_used'      => __( 'Choose from the most used', TEXT_DOMAIN ),
        'popular_items'              => __( 'Popular Items', TEXT_DOMAIN ),
        'search_items'               => __( 'Search Items', TEXT_DOMAIN ),
        'not_found'                  => __( 'Not Found', TEXT_DOMAIN ),
        'no_terms'                   => __( 'No items', TEXT_DOMAIN ),
        'items_list'                 => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation'      => __( 'Items list navigation', TEXT_DOMAIN ),
    );
    $args = array(
        'labels'                     => $labels,
        'hierarchical'               => false,
        'public'                     => false,
        'show_ui'                    => true,
        'show_admin_column'          => true,
        'show_in_nav_menus'          => true,
        'show_tagcloud'              => true,
    );
    register_taxonomy( 'gethere_category', array( 'gethere-post' ), $args );

    $labels = array(
        'name'                       => _x( 'Room Feature', 'Taxonomy General Name', TEXT_DOMAIN ),
        'singular_name'              => _x( 'Room Feature', 'Taxonomy Singular Name', TEXT_DOMAIN ),
        'menu_name'                  => __( 'Room Feature', TEXT_DOMAIN ),
        'all_items'                  => __( 'All Items', TEXT_DOMAIN ),
        'parent_item'                => __( 'Parent Item', TEXT_DOMAIN ),
        'parent_item_colon'          => __( 'Parent Item:', TEXT_DOMAIN ),
        'new_item_name'              => __( 'New Item Name', TEXT_DOMAIN ),
        'add_new_item'               => __( 'Add New Item', TEXT_DOMAIN ),
        'edit_item'                  => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'                => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'                  => __( 'View Item', TEXT_DOMAIN ),
        'separate_items_with_commas' => __( 'Separate items with commas', TEXT_DOMAIN ),
        'add_or_remove_items'        => __( 'Add or remove items', TEXT_DOMAIN ),
        'choose_from_most_used'      => __( 'Choose from the most used', TEXT_DOMAIN ),
        'popular_items'              => __( 'Popular Items', TEXT_DOMAIN ),
        'search_items'               => __( 'Search Items', TEXT_DOMAIN ),
        'not_found'                  => __( 'Not Found', TEXT_DOMAIN ),
        'no_terms'                   => __( 'No items', TEXT_DOMAIN ),
        'items_list'                 => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation'      => __( 'Items list navigation', TEXT_DOMAIN ),
    );

    $args = array(
        'labels'                     => $labels,
        'hierarchical'               => true,
        'public'                     => false,
        'show_ui'                    => true,
        'show_admin_column'          => true,
        'show_in_nav_menus'          => true,
        'show_tagcloud'              => true,
    );
    register_taxonomy( 'room_feature', array( 'room-post' ), $args );

    $labels = array(
        'name'                       => _x( 'Room Utility', 'Taxonomy General Name', TEXT_DOMAIN ),
        'singular_name'              => _x( 'Room Utility', 'Taxonomy Singular Name', TEXT_DOMAIN ),
        'menu_name'                  => __( 'Room Utility', TEXT_DOMAIN ),
        'all_items'                  => __( 'All Items', TEXT_DOMAIN ),
        'parent_item'                => __( 'Parent Item', TEXT_DOMAIN ),
        'parent_item_colon'          => __( 'Parent Item:', TEXT_DOMAIN ),
        'new_item_name'              => __( 'New Item Name', TEXT_DOMAIN ),
        'add_new_item'               => __( 'Add New Item', TEXT_DOMAIN ),
        'edit_item'                  => __( 'Edit Item', TEXT_DOMAIN ),
        'update_item'                => __( 'Update Item', TEXT_DOMAIN ),
        'view_item'                  => __( 'View Item', TEXT_DOMAIN ),
        'separate_items_with_commas' => __( 'Separate items with commas', TEXT_DOMAIN ),
        'add_or_remove_items'        => __( 'Add or remove items', TEXT_DOMAIN ),
        'choose_from_most_used'      => __( 'Choose from the most used', TEXT_DOMAIN ),
        'popular_items'              => __( 'Popular Items', TEXT_DOMAIN ),
        'search_items'               => __( 'Search Items', TEXT_DOMAIN ),
        'not_found'                  => __( 'Not Found', TEXT_DOMAIN ),
        'no_terms'                   => __( 'No items', TEXT_DOMAIN ),
        'items_list'                 => __( 'Items list', TEXT_DOMAIN ),
        'items_list_navigation'      => __( 'Items list navigation', TEXT_DOMAIN ),
    );
    $args = array(
        'labels'                     => $labels,
        'hierarchical'               => true,
        'public'                     => false,
        'show_ui'                    => true,
        'show_admin_column'          => true,
        'show_in_nav_menus'          => true,
        'show_tagcloud'              => true,
    );
    register_taxonomy( 'room_utility', array( 'room-post' ), $args );

}
add_action( 'init', 'custom_taxonomy', 0 );


if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5c8b7637af704',
        'title' => 'Get Here page - Map & Direction',
        'fields' => array(
            array(
                'key' => 'field_5c8b7637cfe6c',
                'label' => 'Map & Direction',
                'name' => 'get_here_page_map_direction',
                'type' => 'file',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'uploadedTo',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => 'pdf',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'templates/gethere.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

endif;
?>